autoInstallPeers: true

catalog:
  tailwindcss: ^4.1.18

onlyBuiltDependencies:
  - '@swc/core'
  - b
  - d
  - e
  - esbuild
  - i
  - l
  - lmdb
  - msgpackr-extract
  - nx
  - s
  - u
  - unrs-resolver
