import {
  LucideAppWindow,
  LucideBadgeCheck,
  LucideBlocks,
  LucideBookOpen,
  LucideBoxes,
  LucideChevronsUpDown,
  LucideBadgeInfo,
  LucideCloudUpload,
  LucideCode,
  LucideColumns2,
  LucideCompass,
  LucideDatabase,
  LucideDownload,
  LucideFlaskConical,
  LucideGitBranch,
  LucideGitCompare,
  LucideGitFork,
  LucideInfo,
  LucideLayers,
  LucideLayoutDashboard,
  LucideLayoutGrid,
  LucideLayoutTemplate,
  LucideListChecks,
  LucideListOrdered,
  LucideMessageSquareWarning,
  LucideMonitor,
  LucideMousePointer2,
  LucideNetwork,
  LucidePackage,
  LucidePalette,
  LucidePanelsTopLeft,
  LucidePlay,
  LucidePlug,
  LucidePuzzle,
  LucideRocket,
  LucideRoute,
  LucideServer,
  LucideSettings,
  LucideShapes,
  LucideShieldCheck,
  LucideSlidersHorizontal,
  LucideSparkles,
  LucideSquareCode,
  LucideSquareStack,
  LucideSunMoon,
  LucideSwatchBook,
  LucideTable2,
  LucideTerminal,
  LucideTreePine,
  LucideTriangleAlert,
  LucideUnplug,
  LucideWorkflow,
  LucideSparkle,
  type LucideIcon,
  type LucideIconData,
} from '@lucide/angular';

const ICON_MAP: Record<string, LucideIcon | LucideIconData> = {
  'app-window': LucideAppWindow,
  'badge-check': LucideBadgeCheck,
  blocks: LucideBlocks,
  'book-open': LucideBookOpen,
  boxes: LucideBoxes,
  'chevrons-up-down': LucideChevronsUpDown,
  'badge-info': LucideBadgeInfo,
  'cloud-upload': LucideCloudUpload,
  code: LucideCode,
  'columns-2': LucideColumns2,
  compass: LucideCompass,
  database: LucideDatabase,
  download: LucideDownload,
  'flask-conical': LucideFlaskConical,
  'git-branch': LucideGitBranch,
  'git-compare': LucideGitCompare,
  'git-fork': LucideGitFork,
  info: LucideInfo,
  layers: LucideLayers,
  'layout-dashboard': LucideLayoutDashboard,
  'layout-grid': LucideLayoutGrid,
  'layout-template': LucideLayoutTemplate,
  'list-checks': LucideListChecks,
  'list-ordered': LucideListOrdered,
  'message-square-warning': LucideMessageSquareWarning,
  monitor: LucideMonitor,
  'mouse-pointer-2': LucideMousePointer2,
  network: LucideNetwork,
  package: LucidePackage,
  palette: LucidePalette,
  'panels-top-left': LucidePanelsTopLeft,
  play: LucidePlay,
  plug: LucidePlug,
  puzzle: LucidePuzzle,
  rocket: LucideRocket,
  route: LucideRoute,
  server: LucideServer,
  settings: LucideSettings,
  shapes: LucideShapes,
  'shield-check': LucideShieldCheck,
  'sliders-horizontal': LucideSlidersHorizontal,
  sparkles: LucideSparkles,
  'square-code': LucideSquareCode,
  'square-stack': LucideSquareStack,
  'sun-moon': LucideSunMoon,
  'swatch-book': LucideSwatchBook,
  'table-2': LucideTable2,
  terminal: LucideTerminal,
  'tree-pine': LucideTreePine,
  'triangle-alert': LucideTriangleAlert,
  unplug: LucideUnplug,
  workflow: LucideWorkflow,
  sparkle: LucideSparkle,
};

export function resolveIcon(id: string): unknown {
  return ICON_MAP[id] ?? id;
}

export const LUCIDE_ICONS = Object.values(ICON_MAP);
